[project]
name = "topologic"
version = "6.0.0"
description = "A software modelling library enabling hierarchical and topological representations of architectural spaces, buildings and artefacts through non-manifold topology"
authors = []
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-64"]

[dependencies]
python = ">=3.8"
occt = "==7.8.0"
cxx-compiler = "*"
cmake = ">=3.24"
ninja = "*"
pybind11 = "==2.13.0"
scipy = "*"
pytest = ">=7.0.0"

[target.linux-64.dependencies]
libuuid = "*"

[tasks]
configure = { cmd = "cmake -B build -S . -DUSE_CONDA_PYBIND11=ON -DCMAKE_BUILD_TYPE=Release -G Ninja" }
build = { cmd = "cmake --build build" }
install = { cmd = "cmake --install build --prefix $CONDA_PREFIX" }
test = { cmd = "pytest TopologicPythonBindings/test" }
test-all = { cmd = "pytest TopologicPythonBindings/test", depends-on = ["configure", "build", "install"] }

debug-configure = { cmd = "cmake -B build-debug -S . -DUSE_CONDA_PYBIND11=ON -DCMAKE_BUILD_TYPE=Debug -G Ninja" }
debug-build = { cmd = "cmake --build build-debug" }
debug-install = { cmd = "cmake --install build-debug --prefix $CONDA_PREFIX" }
debug-test-all = { cmd = "pytest TopologicPythonBindings/test", depends-on = ["debug-configure", "debug-build", "debug-install"] }